# lint analysis
include: package:lint/analysis_options.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error

linter:
  rules:
    # Use parameter order as in json response
    always_put_required_named_parameters_first: true

    avoid_classes_with_only_static_members: false

    sort_constructors_first: true

    prefer_single_quotes: true