name: tizen_api
description: Control your Samsung Tizen TV, writen in pure dart native. Trying the example project is highly encouraged :)
version: 1.0.5
repository: https://github.com/CyBear-Jinni/tizen_api

exclude:
  - example/

environment:
  sdk: ^3.5.3


dependencies:
  dio: ^5.4.3+1
  web_socket_channel: ^3.0.1


dev_dependencies:
  # Collection of lint rules for Dart and Flutter projects.
  lint: ^2.3.0
  test: ^1.25.2