name: tizen_api
description: Control your Samsung Tizen TV, writen in pure dart native. Trying the example project is highly encouraged :)
version: 1.0.2
repository: https://github.com/CyBear-Jinni/tizen_api

environment:
  sdk: ^3.3.3


dependencies:
  dio: ^5.4.3+1
  network_info_plus: ^5.0.3
  web_socket_channel: ^2.4.5


dev_dependencies:
  # Collection of lint rules for Dart and Flutter projects.
  lint: ^2.3.0
  test: ^1.25.2