name: tizen_api
description: Control your Samsung Tizen TV, writen in pure dart native. Trying the example project is highly encouraged :)
version: 1.0.1
repository: https://github.com/CyBear-Jinni/tizen_api

environment:
  sdk: ^3.3.3


dependencies:
  network_info_plus: ^5.0.3
  dio: ^5.4.3+1
  web_socket_channel: ^2.4.5


dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
