name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: dart pub get

      - name: Check Publish Warnings
        run: dart pub publish --dry-run

  publish:
    needs: 'tests'
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: git-elliot/setup-dart/.github/workflows/publish.yml@main # Added build_runner step
    with:
      environment: 'pub.dev'